# Generated by Django 2.1.7 on 2019-03-10 19:50

import apps.agreement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('stop_date', models.DateField(verbose_name='Stop date')),
                ('debit', models.PositiveIntegerField(verbose_name='Debit')),
                ('credit', models.PositiveIntegerField(verbose_name='Credit')),
            ],
            options={
                'verbose_name': 'Agreement',
                'verbose_name_plural': 'Agreements',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=3, verbose_name='3-alpha ISO code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('stop_date', models.DateField(verbose_name='Stop date')),
                ('status', models.CharField(choices=[('N', 'New'), ('A', 'Active'), ('R', 'Reconciliation'), ('C', 'Closed')], max_length=1, verbose_name='Status')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='agreement.Agreement', verbose_name='Agreement')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'ordering': ('-stop_date',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='agreement.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='agreement.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='negotiator',
            field=models.ForeignKey(on_delete=models.SET(apps.agreement.models.get_sentinel_user), related_name='agreements', to=settings.AUTH_USER_MODEL, verbose_name='Negotiator'),
        ),
    ]
